version: '3.9'
services:
  api:
    image: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.18
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - /data/pgadmin:/root/.pgadmin
    networks:
      - postgres

volumes:
  postgres_data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
